version: '3.8'

services:
  api:
    image: matheusls0/marketplace-boilerplate:latest
    container_name: marketplace_boilerplate
    restart: always
    build: 
      context: .
      target: production
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
    #networks:
    #  - postgres
    #  - redis
    #volumes:
    #  - .:/app
    
